presubmits:
  - name: pull-logicalcluster-verify
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kcp-dev/logicalcluster.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.20-node-18-6
          command:
            - make
            - verify-imports
            - verify-boilerplate

  - name: pull-logicalcluster-lint
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kcp-dev/logicalcluster.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.20-node-18-6
          command:
            - make
            - lint

  - name: pull-logicalcluster-test
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kcp-dev/logicalcluster.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.20-node-18-6
          command:
            - make
            - test
